In [2]:
from tabula import read_pdf
import pandas as pd

In [4]:
filename = 'Invoice 1014647'
df = read_pdf(filename+'.pdf',multiple_tables=True)
df

[                          0   1                         2   3  \
 0          C u s To M E r : NaN       D  EL i vE r  T o : NaN
 1  FRIENDLY GROCER WESTMEAD NaN  FRIENDLY GROCER WESTMEAD NaN
 2                SHOP 11-12 NaN                SHOP 11-12 NaN
 3         24 RAILWAY PARADE NaN         24 RAILWAY PARADE NaN
 4           WESTMEADNSW2145 NaN           WESTMEADNSW2145 NaN
 5                       NaN NaN                       NaN NaN

                                  4  \
 0   C u s T o M E r a C C : 105826
 1  D E L iv E r T o  a C C :105826
 2                 o r D E r n  o :
 3               o P E r a To r :49
 4                              NaN
 5               MOSTLY PAYS DRIVER

                                                    5
 0                                        TAX INVOICE
 1                                                NaN
 2         T r a n s a C T io n T y P E : Tax Invoice
 3           T r a n s a C T io n D a T E : 14 Aug 15
 4  T r a n s a C T io n n u M B E r :  10  1  4  ...
 5                                     * Reprint 32 *  ,
                                                    0   \
 0                                                 NaN
 1                                                CoDE
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN
 14                                               7058
 15                                               7059
 16                                               7052
 17                                    B a T C h n o :
 18                                                NaN
 19                                  T E r ri To r y :
 20                                                NaN
 21                                                NaN
 22  rt ra ns a cti on  a c co un t.  M o re  in fo...
 23                                                NaN
 24                                       W  Ei g hT :

                                       1                           2   \
 0                                    QTy                         NaN
 1                                shiPPED                 DEsCriPTion
 2                                    NaN                         NaN
 3                                    NaN                         NaN
 4                                    NaN                         NaN
 5                                    NaN                         NaN
 6                                    NaN                         NaN
 7                                    NaN                         NaN
 8                                    NaN                         NaN
 9                                    NaN                         NaN
 10                                   NaN                         NaN
 11                                   NaN                         NaN
 12                                   NaN                         NaN
 13                                    F3                         NaN
 14  6.000 KRC CHICKEN BREAST SHAVED 100G                         NaN
 15  6.000 KRC LEG HAM HONEY SHAVED 100GM                         NaN
 16        6.000 DON FRANKS SKIN ON 500GM                         NaN
 17                 T oT a L o u T Er s :                      18.000
 18                                   NaN                         NaN
 19                     2D E Li vE r E D:  18.000  T e le p ho n e  &
 20                                   NaN                         NaN
 21                                   NaN                         NaN
 22                                8B  Cy                        ar :
 23                                   NaN                         NaN
 24                          0.00C Tn s :                           0

                                                    3   \
 0                                      suggEsTEDouTEr
 1                                           rETaiLQTy
 2         Credit Card Surcharge from 1st January 2014
 3                                Visa/Mastercard - 1%
 4                                    AMEX- 2.2% + GST
 5                Price Rise: August 31st - Go Natural
 6                 September 1st - Key Pharmaceuticals
 7                                                 NaN
 8                             October 3rd - Funtastic
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12            visit jbmetro.com.au for deals and news
 13                                                NaN
 14                                            3.60010
 15                                            3.60010
 16                                            4.90010
 17                         B I LL E R C O D E : 67652
 18                                     R E F :1058262
 19                In te rn e t  B a nk in g  –B PA Y®
 20  Contact your bank or financial institution to ...
 21  payment from your cheque, savings, debit, cred...
 22                                                NaN
 23                          Cash   ChEQuE   C/CarD
 24                                        s ig n ED :

                           4                                  5   \
 0                        NaN                                NaN
 1                    BarCoDE                                NaN
 2                        NaN                                NaN
 3                        NaN                                NaN
 4                        NaN                                NaN
 5                        NaN                                NaN
 6                        NaN                                NaN
 7          9th - Park Avenue                                NaN
 8                        NaN                                NaN
 9    5th - Colgate Palmolive                                NaN
 10  12th - Arnotts Campbells                                NaN
 11            - Mars funsize                                NaN
 12                       NaN                                NaN
 13                       NaN                                NaN
 14                       NaN                                NaN
 15                       NaN                                NaN
 16                       NaN                                NaN
 17                       NaN                    D u E D a T E :
 18                       NaN                         T Er M s :
 19                       NaN                                NaN
 20                       NaN                                NaN
 21                       NaN                                  a
 22                       NaN  (in C Lu Di ng T hi s in vo iC E)
 23                       NaN                                NaN
 24                       NaN                                NaN

                  6      7   8                                   9   10  \
 0               NaN    NaN NaN                           nET PriCE NaN
 1             gsT %  ProMo NaN                              Ex gsT NaN
 2               NaN    NaN NaN                                 NaN NaN
 3               NaN    NaN NaN                                 NaN NaN
 4               NaN    NaN NaN                                 NaN NaN
 5               NaN    NaN NaN                                 NaN NaN
 6               NaN    NaN NaN                                 NaN NaN
 7               NaN    NaN NaN                                 NaN NaN
 8               NaN    NaN NaN                                 NaN NaN
 9               NaN    NaN NaN                                 NaN NaN
 10              NaN    NaN NaN                                 NaN NaN
 11              NaN    NaN NaN                                 NaN NaN
 12              NaN    NaN NaN                                 NaN NaN
 13              NaN    NaN NaN                                 NaN NaN
 14             0.00    NaN NaN                               2.660 NaN
 15             0.00    NaN NaN                               2.660 NaN
 16             0.00    NaN NaN                               3.600 NaN
 17        11 Sep 15    NaN NaN  n  o n  T a x a B L E a  M o u n T NaN
 18          28 days    NaN NaN                                 NaN NaN
 19              NaN    NaN NaN          T a x a B L E a  M o u n T NaN
 20              NaN    NaN NaN                                 NaN NaN
 21  CCounT B aLanCE      : NaN                            (Ex GST) NaN
 22              NaN    NaN NaN                               g s T NaN
 23              NaN    NaN NaN                                 NaN NaN
 24              NaN    NaN NaN             T o T a L  in C  g  s T NaN

            11
 0         NaN
 1   ExTEnsion
 2         NaN
 3         NaN
 4         NaN
 5         NaN
 6         NaN
 7         NaN
 8         NaN
 9         NaN
 10        NaN
 11        NaN
 12        NaN
 13        NaN
 14      15.96
 15      15.96
 16      21.60
 17      53.52
 18        NaN
 19       0.00
 20        NaN
 21        NaN
 22       0.00
 23        NaN
 24      53.50  ]