In [220]:
import pandas as pd
import tabula

In [221]:
file_name = 'metcash_1'
dataframe_list = tabula.read_pdf(file_name+'.pdf',multiple_tables=True,pages='all',pandas_options={'header':None})
num_of_df = len(dataframe_list)

In [200]:
df=dataframe_list[0]
df

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,Line,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No.,Product ID,Product Description,NaN,IND,Qty,NaN,UOM,PackQty,NaN,...,GST $,Total Cost ITEM,NaN,Total Val EXTENDED,NaN,Landed Unit Cost,NaN,SuggSell,NaN,GP%
2,NaN,NaN,* CONFECTIONERY*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,-----------------------------,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00101,19106,ALLENS CHICOS190GM,NaN,P,NaN,1,CSE,12,NaN,...,1.73,19.02,NaN,19.02,NaN,1.58,NaN,3.33,NaN,52.4
5,00102,25220,ALLENS PARTY MIX190GM,NaN,P,NaN,1,CSE,12,NaN,...,1.73,19.02,NaN,19.02,NaN,1.58,NaN,3.33,NaN,52.4
6,00103,25288,ALLENS PARTY MIX RETRO190GM,NaN,P,NaN,1,CSE,12,NaN,...,1.73,19.02,NaN,19.02,NaN,1.58,NaN,3.33,NaN,52.4
7,00104,21763,ALLENS STRAWBERRIES & CRM190GM,NaN,P,NaN,1,CSE,12,NaN,...,1.73,19.02,NaN,19.02,NaN,1.58,NaN,3.33,NaN,52.4
8,00105,494974,B/GOLD BANANAS200GM,NaN,NaN,NaN,1,CSE,12,NaN,...,1.31,14.42,NaN,14.42,NaN,1.20,NaN,1.73,NaN,30.5
9,00106,386171,B/GOLD SNAKES500GM,NaN,NaN,NaN,1,CSE,12,NaN,...,2.45,26.96,NaN,26.96,NaN,2.24,NaN,3.33,NaN,32.5
10,00107,430556,B/GOLD SPEARMINT LEAVES 200GM,NaN,NaN,NaN,1,CSE,12,NaN,...,1.80,19.75,NaN,19.75,NaN,1.64,NaN,2.48,NaN,33.6
11,00108,312622,NAT/CONF DINOSAURS260GM,NaN,P,NaN,1,CSE,18,NaN,...,3.61,39.74,NaN,39.74,NaN,2.20,NaN,2.49,NaN,11.3
12,00109,606424,PAS JUBES350GM,NaN,P,NaN,1,CSE,12,NaN,...,2.51,27.58,NaN,27.58,NaN,2.29,NaN,2.49,NaN,7.7
13,00110,311207,PAS M/MALLOWS VAN/RSPBRY 280GM,NaN,P,NaN,1,CSE,10,NaN,...,2.09,22.99,NaN,22.99,NaN,2.29,NaN,2.49,NaN,7.7
14,00111,480129,B/GOLD CHOC CT HONEYCOMB 150GM,NaN,NaN,NaN,1,CSE,24,NaN,...,3.14,34.49,NaN,34.49,NaN,1.43,NaN,3.12,NaN,53.9
15,00112,382240,DORITOS SALSA HOT300GM,NaN,P,NaN,1,CSE,8,NaN,...,.00,16.30,NaN,16.30,NaN,2.03,NaN,2.50,NaN,18.5
16,00113,362986,MISSION BBQ CHIP SMKY SPCY230G,NaN,NaN,NaN,1,CSE,6,NaN,...,1.26,13.81,NaN,13.81,NaN,2.30,NaN,3.96,NaN,41.9
17,00114,2683,MISSION CORN CHP EX CHSE 230GM,NaN,NaN,NaN,1,CSE,6,NaN,...,1.26,13.81,NaN,13.81,NaN,2.30,NaN,3.96,NaN,41.9
18,00115,363005,MISSION CORN CHIP NACHOS 230G,NaN,NaN,NaN,1,CSE,6,NaN,...,1.26,13.81,NaN,13.81,NaN,2.30,NaN,3.96,NaN,41.9
19,00116,299162,SMITHS CRINKL CHS/ONION 170GM,NaN,P,NaN,1,CSE,12,NaN,...,2.38,26.16,NaN,26.16,NaN,2.18,NaN,2.50,NaN,12.8
20,00117,17489,THINS CHIP LTE TANGY175GM,NaN,P,NaN,1,CSE,12,NaN,...,2.04,22.45,NaN,22.45,NaN,1.87,NaN,2.00,NaN,6.5
21,00118,17366,THINS CHIP ORIGINAL175GM,NaN,P,NaN,1,CSE,12,NaN,...,2.04,22.45,NaN,22.45,NaN,1.87,NaN,2.00,NaN,6.5
22,00119,17277,THINS CHIP SLT&VIN175GM,NaN,P,NaN,1,CSE,12,NaN,...,2.04,22.45,NaN,22.45,NaN,1.87,NaN,2.00,NaN,6.5
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,352.74,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,24.40,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,377.14,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,36.11,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,413.25,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
print(findColumIndex(df,'Line'))

0

In [222]:
def isPresent(df,str):
    result_ser = df.iloc[:,0].str.contains(str)
    result_list = result_ser.tolist()
    for i in result_list:
        if i == True:
            return True
    return False

In [223]:
def findTableStartIndex(df,starting_index):
    start_index = starting_index
    result_list = df.iloc[start_index:,0].str.contains('NaN').tolist()
    for item in result_list:
        if item != False:
            start_index = start_index + 1
        else:
            return start_index
    return start_index

In [224]:
def findEndingIndex(df,starting_index):
    end_index = starting_index
    result_list = df.iloc[end_index:,0].str.contains('NaN').tolist()
    for item in result_list:
        if item == False:
            end_index = end_index + 1
        else:
            return end_index
    return end_index

In [225]:
def findColumIndex(df,strs):
    #df.columns[df.isin(['Line'])]
    result_list = []
    num_of_col = df.shape[1]
    for col_index in range(0,num_of_col):
        result_list=df.iloc[:,col_index].astype(str).str.contains(strs).tolist()
        for value in result_list:
            if value == True:
                return col_index
    return -1

In [229]:
starting_str = 'Line'
ending_str = 'EFT PAYMENT DETAILS'

Line_No = []
Product_ID = []
Product_Description = []
IND = []
Qty = []
UOM = []
Pack_Qty = []
weight = []
GST_p = []
cost = []
Mrgn = []
GST_d = []
Total_costitem = []
total_valExtended = []
Landed_unit_cost = []
sugg_sell = []
GP_p = []


Line_No_final = []
Product_ID_final = []
Product_Description_final = []
IND_final = []
Qty_final = []
UOM_final = []
Pack_Qty_final = []
weight_final = []
GST_p_final = []
cost_final = []
Mrgn_final = []
GST_d_final = []
Total_costitem_final = []
total_valExtended_final = []
Landed_unit_cost_final = []
sugg_sell_final = []
GP_p_final = []


coulum_names = ['Line','Product ID','Product Description','IND','Qty','UOM','Pack','Weight','GST','Cost','Mrgn','GST',
                'Total Cost ITEM','Total Val EXTENDED','Landed Unit Cost','SuggSell','GP%','','','','','','','','']
colum_indexes = []
print(len(df.columns))

24

In [233]:
for index in range(0,num_of_df):
    df = dataframe_list[index]
    result = isPresent(df,starting_str)
    if result == True:
        for index_c in range(0,len(df.columns)):
            colum_indexes.append(findColumIndex(df,coulum_names[index_c]))
            
        start_index = (df.index[df.iloc[:,0].str.contains(starting_str) == True])
        start_index = findTableStartIndex(df,start_index[0]+2)
        end_index   = findEndingIndex(df,starting_index=start_index)
        table_df = df[start_index:end_index]
        print("***************   Data Frame:",index,'  ********************* \n \n')
        print(table_df)
        print('\n \n \n \n \n')
        
        Line_No = table_df.iloc[:,colum_indexes[0]].tolist()
        Product_ID = table_df.iloc[:,colum_indexes[1]].tolist() 
        Product_Description = table_df.iloc[:,colum_indexes[2]].tolist()
        IND = table_df.iloc[:,colum_indexes[3]].tolist() 
        Qty = table_df.iloc[:,colum_indexes[4]].tolist()
        UOM = table_df.iloc[:,colum_indexes[5]].tolist()
        Pack_Qty = table_df.iloc[:,colum_indexes[6]].tolist()
        weight = table_df.iloc[:,colum_indexes[7]].tolist() 
        GST_p = table_df.iloc[:,colum_indexes[8]].tolist()
        cost = table_df.iloc[:,colum_indexes[9]].tolist()
        Mrgn = table_df.iloc[:,colum_indexes[10]].tolist()
        GST_d = table_df.iloc[:,colum_indexes[11]].tolist()
        Total_costitem = table_df.iloc[:,colum_indexes[12]].tolist()
        total_valExtended = table_df.iloc[:,colum_indexes[13]].tolist()
        Landed_unit_cost = table_df.iloc[:,colum_indexes[14]].tolist()
        sugg_sell = table_df.iloc[:,colum_indexes[15]].tolist()
        GP_p = table_df.iloc[:,colum_indexes[16]].tolist()
        
        colum_indexes.clear()
        
        Line_No_final = Line_No_final + Line_No
        Product_ID_final = Product_ID_final + Product_ID
        Product_Description_final = Product_Description_final + Product_Description
        IND_final = IND_final + IND
        Qty_final = Qty_final + Qty
        UOM_final = UOM_final + UOM
        Pack_Qty_final = Pack_Qty_final + Pack_Qty
        weight_final = weight_final + weight
        GST_p_final = GST_p_final + GST_p
        cost_final = cost_final + cost
        Mrgn_final = Mrgn_final + Mrgn
        GST_d_final = GST_d_final + GST_d
        Total_costitem_final = Total_costitem_final + Total_costitem
        total_valExtended_final = total_valExtended_final + total_valExtended
        Landed_unit_cost_final = Landed_unit_cost_final + Landed_unit_cost
        sugg_sell_final = sugg_sell_final + sugg_sell
        GP_p_final = GP_p_final + GP_p

SyntaxError: invalid syntax (<ipython-input-233-cb0a22bb1a75>, line 18)

In [231]:

data_dic = {'LineNo':Line_No,'Product ID':Product_ID,'Product Description':Product_Description,"IND":IND,"Qty":Qty,'UOM':UOM,
            'Pack':Pack_Qty,'Weight':weight,'GST%':GST_p,'Cost':cost,'Mrgn':Mrgn,'GST$':GST_d,'Total Cost ITEM':Total_costitem,
            'Total Val EXTENDED':total_valExtended,'Landed Unit Cost':Landed_unit_cost,'SuggSell':sugg_sell,'GP%':GP_p
           }

In [232]:
dataframe_result = pd.DataFrame(data=data_dic)
dataframe_result

,Cost,GP%,GST$,GST%,IND,Landed Unit Cost,LineNo,Mrgn,Pack,Product Description,Product ID,Qty,SuggSell,Total Cost ITEM,Total Val EXTENDED,UOM,Weight
0,"[16.08, 16.08, 16.08, 16.08, 12.19, 22.83, 16....","[52.4, 52.4, 52.4, 52.4, 30.5, 32.5, 33.6, 11....","[2.510 10.00, 2.510 10.00, 2.530 10.00, 2.5...","[2.510 10.00, 2.510 10.00, 2.530 10.00, 2.5...","[P, P, P, P, nan, nan, nan, P, P, P, nan, P, n...","[1.58, 1.58, 1.58, 1.58, 1.20, 2.24, 1.64, 2.2...","[00101, 00102, 00103, 00104, 00105, 00106, 001...","[1.21, 1.21, 1.21, 1.21, nan, 1.68, 1.24, 2.45...","[12, 12, 12, 12, 12, 12, 12, 18, 12, 10, 24, 8...","[ALLENS CHICOS190GM, ALLENS PARTY MIX190GM, AL...","[19106, 25220, 25288, 21763, 494974, 386171, 4...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[3.33, 3.33, 3.33, 3.33, 1.73, 3.33, 2.48, 2.4...","[19.02, 19.02, 19.02, 19.02, 14.42, 26.96, 19....","[19.02, 19.02, 19.02, 19.02, 14.42, 26.96, 19....","[CSE, CSE, CSE, CSE, CSE, CSE, CSE, CSE, CSE, ...","[2.510 10.00, 2.510 10.00, 2.530 10.00, 2.5..."
1,"[21.10, 76.56, 27.22, 39.39, 39.39, 73.92, 11....","[28.6, 15.2, 29.2, 12.0, 12.0, 30.2, 10.9, 39....","[10.00, .00, .00, .00, .00, .00, .00, 10.00, ....","[10.00, .00, .00, .00, .00, .00, .00, 10.00, ....","[U/TOBY YGT TOPPS STRWBRY 185GM, NES MILO, NES...","[28.6, 15.2, 29.2, 12.0, 12.0, 30.2, 10.9, 39....","[00201, 00202, 00203, 00204, 00205, 00206, 002...","[1.56, 5.52, 2.00, 2.85, 2.85, 5.32, .88, 1.81...","[10, 12, 12, 6, 6, 12, 4, 12, 10, 12, 12, 1, 1...","[nan, 460GM, 250GM, nan, nan, 150GM, 10PK, nan...","[435572, 634516, 10259, 10144, 450954, 10916, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[28.6, 15.2, 29.2, 12.0, 12.0, 30.2, 10.9, 39....","[28.6, 15.2, 29.2, 12.0, 12.0, 30.2, 10.9, 39....","[28.6, 15.2, 29.2, 12.0, 12.0, 30.2, 10.9, 39....","[CSE, CSE, CSE, CSE, CSE, CSE, CSE, CSE, CSE, ...","[2.260, 6.730, 3.830, 2.340, 2.350, 6.390, .78..."
2,"[20.17, 9.81, 12.30, 17.70, 32.64, 23.94, 14.8...","[13.3, 22.5, 8.6, 28.6, 24.3, 16.5, 29.5, 25.9...","[6.840 10.00, 1.610 10.00, 2.410 10.00, 3.8...","[6.840 10.00, 1.610 10.00, 2.410 10.00, 3.8...","[nan, P, P, nan, nan, nan, nan, nan, nan, nan,...","[13.3, 22.5, 8.6, 28.6, 24.3, 16.5, 29.5, 25.9...","[00301, 00302, 00303, 00304, 00305, 00306, 003...","[1.49, nan, nan, 1.31, 2.38, 1.76, 1.11, 2.11,...","[12, 12, 8, 12, 10, 24, 6, 12, 12, 6, 6, 6, 4,...","[500GM, 100GM, 250GM, 20S, nan, nan, TWN, nan,...","[348270, 11271, 344624, 59978, 8281, 485064, 3...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[13.3, 22.5, 8.6, 28.6, 24.3, 16.5, 29.5, 25.9...","[13.3, 22.5, 8.6, 28.6, 24.3, 16.5, 29.5, 25.9...","[13.3, 22.5, 8.6, 28.6, 24.3, 16.5, 29.5, 25.9...","[CSE, CSE, CSE, CSE, CSE, CSE, CSE, CSE, CSE, ...","[6.840 10.00, 1.610 10.00, 2.410 10.00, 3.8..."
3,"[20.21, 20.21, 17.78, 17.78]","[.2, .2, 12.2, 12.2]","[51.930 10.00, 33.660 10.00, 17.270 10.00, ...","[51.930 10.00, 33.660 10.00, 17.270 10.00, ...","[P, P, P, P]","[2.98, 2.98, 2.62, 2.62]","[00401, 00402, 00403, 00404]","[1.49, 1.49, 1.31, 1.31]","[8, 8, 8, 8]","[COCA COLA2L, COCA COLA N/SUG2L, FANTA ORANGE2...","[14570, 921743, 13621, 51352]","[nan, nan, nan, nan]","[2.99, 2.99, 2.99, 2.99]","[23.87, 23.87, 21.00, 21.00]","[71.61, 47.74, 21.00, 63.00]","[CSE, CSE, CSE, CSE]","[51.930 10.00, 33.660 10.00, 17.270 10.00, ..."