In [1]:
import pandas as pd
import tabula

In [11]:
filename = 'Bonfect_2'
raw_df = tabula.read_pdf(filename+'.pdf',multiple_tables=True,pages='all')

In [12]:
print(len(raw_df))

4

In [14]:
raw_df[1]

,0,1,2,3,4,5,6,7,8,9,10
0,NaN,QTY,SUGGESTED OUTER,NaN,NaN,WHOLESALE,NaN,NaN,NaN,NET PRICE,NaN
1,CODE,SHIPPED DESCRIPTION,RETAIL QTY BARCODE,NaN,GST %,EX GST,NaN,PROMO,DISCOUNT,EX GST,EXTENSION
2,NaN,NaN,All imported items are not for individual sale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,UNLESS you label individually.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,"EFT Details: CBA, BSB 062 232, A/C 1003 8531.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6023935,2.000 KINDER SURPRISE SMURF,2.45024,NaN,10.00,24.000,NaN,NaN,10.000%,21.600,47.52
6,602743,1.000 WONKA GOBSTOPPER 140G*12,3.15012079200619091 10.00,NaN,NaN,21.000,NaN,NaN,8.000%,19.320,21.25
7,602774,1.000 WONKA RAINBOW NERDS 141G*12,3.15012079200558338 10.00,NaN,NaN,21.000,NaN,NaN,8.000%,19.320,21.25
8,602773,1.000 WONKA RUNTS 141G*12,3.15012079200472146 10.00,NaN,NaN,21.000,NaN,NaN,8.000%,19.320,21.25
9,602750,2.000 WARHEADS SOUR CUBES 113G*12,3.15012032134232248 10.00,NaN,NaN,21.000,NaN,NaN,8.000%,19.320,42.50
10,6066673,1.000 WRI EXTRA L LIME TUB 6,5.4306 9300613110563 10.00,NaN,NaN,17.760,NaN,NaN,10.000%,15.984,17.58
11,6015343,1.000 EXTRA ACTIVE PEPPERMINT 24,2.30024,93613378 10.00,NaN,37.600,NaN,NaN,10.000%,33.840,37.22
12,602763,1.000 WONKA NERDS ROPE RAINBOW 24,1.32024079200173067 10.00,NaN,NaN,22.070,NaN,NaN,8.000%,20.304,22.33
13,602837,1.000 ZAPPO STRAWBERRY 21G *60,0.60060 9318082065550 10.00,NaN,NaN,25.160,NaN,NaN,10.000%,22.644,24.91
14,602832,1.000 ZAPPO COLA 21G*60,0.60060 9327776010165 10.00,NaN,NaN,25.160,NaN,NaN,10.000%,22.644,24.91
15,602065,1.000 WACKY PUSH POP *24,1.31024041116005343 10.00,NaN,NaN,22.000,NaN,NaN,10.000%,19.800,21.78
16,6063375,1.000 ANTICOL EXTRA STRONG *36,1.73036,NaN,10.00,45.100,NaN,NaN,8.000%,41.492,45.64
17,600572,1.000 CAD CARAMELLO KOALA 15G 72,0.51072,93617482 10.00,NaN,25.550,NaN,NaN,10.000%,22.995,25.30
18,600561,1.000 CAD CHOMP CARAMEL 30G*63,1.09063 9300617323419 10.00,NaN,NaN,41.210,NaN,NaN,10.000%,37.089,40.80
19,601764,1.000 NES WONKA NERDS NEON *24,1.32024 9300605247895 10.00,NaN,NaN,22.070,NaN,NaN,8.000%,20.304,22.33
20,601138,1.000 NES WONKA GOBSTOPPERS 24*50G,1.32024079200230401 10.00,NaN,NaN,24.000,NaN,NaN,8.000%,22.080,24.29
21,600395,1.000 BUBBLE TAPE GRAPE 12,2.10012,93613590 10.00,NaN,17.840,NaN,NaN,10.000%,16.056,17.66
22,NaN,** CONTINUED ON PAGE 2 **,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,BATCH NO:,TOTAL OUTERS:,NaN,DUE DATE:,NaN,NaN,NaN,NON TAXABLE AMOUNT,NaN,NaN,NaN
24,NaN,NaN,? CASH ? CHEQUE ? C/CARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,TERMS:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,TERRITORY:,DELIVERED:,____________________________________,NaN,NaN,NaN,NaN,NaN,TAXABLE AMOUNT,NaN,NaN
27,NaN,NaN,NaN,A,CCOUNT B ALANCE,:,NaN,NaN,NaN,(Ex GST),NaN
28,NaN,NaN,SIGNED: _____________________________,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,RUN:,BY CAR:,NaN,(INCLUDING THIS INVOICE),NaN,NaN,NaN,NaN,NaN,GST,NaN
30,NaN,NaN,PRINT:_____________________________,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,1.0015,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL INC GST,NaN,NaN

In [1]:
import pandas as pd
import tabula

filename = 'abc_1'
raw_df = tabula.read_pdf(filename+'.pdf',multiple_tables=True,pages='all')

In [3]:
print(raw_df)

[]